name: Deploy para Hostinger

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Baixando código-fonte (Checkout)
      uses: actions/checkout@v4
      
    - name: Configurando Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Instalando dependências (NPM)
      run: npm ci --legacy-peer-deps

    - name: Gerando Build Estático Next.js (out/)
      run: npm run build

    - name: Realizando Upload via FTP (Script customizado)
      env:
        FTP_HOST: "147.93.14.87"
        FTP_USER: "u786839041.paganicustomsite"
        FTP_PASSWORD: "1q2w3e4r@@@SK"
      run: node fix_deploy.mjs
